#!/bin/bash

# Code is poetry

# Code to extract EDID from file generated by FixEDID app
# Author: black.dragon74 <www.osxlatitude.com>

# Clear
clear

inputFile="$1"

echo -e "EDID/Base64 to HEX convertor by black.dragon74 <www.osxlatitude.com>" && sleep 1

if [[ ! $1 ]];
	then
	echo -e "No input file specified"
	echo "Rerun as: $0 <InputFileHere>"
	exit
fi

plCheck="$(plutil $inputFile | grep "OK" | sed 's/://g' | awk '{print $2}')"

# Check if the input is a valid PLIST
if [ "$plCheck" = "OK" ];
	then
	echo -e "PLIST File is Good to go!\nChecking for EDID entry"
	/usr/libexec/PlistBuddy -c "Print IODisplayEDID" $inputFile &>~/tmpED
	if [ "$(cat ~/tmpED | awk '{print $5}')" = "Not" ];
		then
		echo -e "Entry IODisplayEDID does not exist."
		rm ~/tmpED
		exit
	fi
	rm ~/tmpED
	echo -e "Found EDID"
	echo -e "Decoding Base64 to HEX" && sleep 1
	echo -e "Removing checksum (last 2 digits)" && sleep 0.5
	echo -e "EDID to inject is :-" && sleep 0.5
	echo -e "\n$(/usr/libexec/PlistBuddy -c "Print IODisplayEDID" $inputFile | hexdump -v -e '/1 "%02x" ' | rev | cut -c 3- | rev)\n" | awk '{print toupper($0)}'
else
	echo -e "Input is not a valid PLIST file."
	exit 1
fi
# EOF